### ISSUE TITLE
Interesting concept 

### ISSUE THREAD

**Issue by ernesst** [liu-xiao-guo/filebrowser-ubuntuphone#1]
Hey, 
Interesting concept the way to navigate through the apps. 
Are you aware about ubports.com project https://www.ubports.com/ ?

I guess the person in charge of the filemanager app would be interesting by your work : https://github.com/ubports/filemanager-app

**Comment by liu-xiao-guo** [comment]
yes, I know the project. The project was a quick mock-up, and it was very convenient for me to debug some of the issues when developing applications. you can just use your fingers to swipe left and right :)
